### ISSUE TITLE
rule:GalaxySpringBeanAvoidNonFinalVariables

### ISSUE THREAD

**Issue by hanlei19878** [dcfs-pmo/dcfs-java-custom-rules#3]
新核心应用不允许在服务Bean中声明非Final成员变量。
Spring容器默认为单实例模式，多线程运行的时不安全，产生串值问题。
  1.检查Spring服务Bean下非自动注入的非final成员变量
  2.日志类与java.lang.ThreadLocal类不检查
  3.新核心指标类与工厂类不检查
推荐使用方式：
    1. 增加Final修饰符;
    2. 使用局部变量替换;
    3. 必要情况下使用ThreadLocal;
错误代码：
@Component
public class test{
    int a ;
    String b = "AAA";
    int m1(String var1 ,int var2){
        a=0;
        if(var1.equals(b)){
            a=a+var2;
        }
        return a;
    }
}

正确代码：
@Component
public class test{
    static final String b = "AAA";
    int m1(String var1 ,int var2){
        int a=0;
        if(var1.equals(b)){
            a=a+var2;
        }
        return a;
    }
}

已实现 hanleia

**Comment by hanlei19878** [comment]
fork库 : https://github.com/hanlei19878/dcfs-java-custom-rules
hanleia

**Comment by dcfspmo** [comment]
规则待评审以及验证
