### ISSUE TITLE
ESC在p端接收返回数据量过大的情况下，解析返回数据时失败

### ISSUE THREAD

**Issue by gzwz** [dcfs-pmo/dcfs-java-custom-rules#9]
ESC在p端接收返回数据量过大的情况下，解析返回数据时失败，
原因是com.dc.messageserver.util.FormatHeaderUtil.writeSize 此方法中扩容的计算有问题
......
        private static final int _10240 = 1048576;
	private static final int LENGTH_SIZE = 4;
	protected byte[] container = new byte[_10240];
......
private int writeSize(int length, int offset) {
		while (**offset + 2** > container.length - 1) {
			enlargeSelf();
		}
		**byte[] intLen = new byte[4];**
		intLen = IntByteConvertor.int2Byte(length);
		int count = offset;
		for (int i = 0; **i < 4;** i++) {
			container[count] = intLen[i];
			count++;
		}
		offset += LENGTH_SIZE;
		return offset;
	}
此类声明容器大小为 1048576 但是如果数据是在 offset= 1048593 的时候 达不到扩容的条件，offset指针也只增加2, 但是后续代码 container[count] = intLen[i]; 却需要遍历 offset=1048573+3 ==> offset=1048576 此时 container[count] 越界一位，导致P端数组越界，后续引发一系列问题，如果c到p 使用协议是http, 还会导致 jetty 500异常

解决版本  原方法 中改成 **while (**offset + 3** > container.length - 1)** 
private int writeSize(int length, int offset) {
		while (**offset + 3** > container.length - 1) {
			enlargeSelf();
		}
		byte[] intLen = new byte[4];
		intLen = IntByteConvertor.int2Byte(length);
		int count = offset;
		for (int i = 0; **i < 4;** i++) {
			container[count] = intLen[i];
			count++;
		}
		offset += LENGTH_SIZE;
		return offset;
	}

**Comment by dcfspmo** [comment]
请补充以下内容：
[Issues 内容需要包括：注明是否自己实现该rule，如自己实现，则注明预计实现日期 ]

[Issues 内容需要包括：规则提交人ITCODE ]

另外，请给规则起一个清晰的标题，例如：rule:GalaxySpringBeanAvoidNonFinalVariables

**Comment by dcfspmo** [comment]
@gzwz

**Comment by dcfspmo** [comment]
过期关闭
